#!/usr/bin/env bash
BAT=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep "percentage" | grep -oP "[0-9]+")
if [[ ! -f /tmp/CHARGE_SHUTDOWN ]]; then
  echo "0" > /tmp/CHARGE_SHUTDOWN
fi

if  [[ "$(cat /tmp/CHARGE_SHUTDOWN)" -ne "1" && $BAT -lt "20" && "$(cat /sys/class/power_supply/BAT0/status)" = "Discharging" ]]; then
  echo "1" > /tmp/CHARGE_SHUTDOWN
  notify-send -u critical -t 0 "Critical battery: shutdown in 5 minutes" -a "System"
  (sleep 240; unset CHARGE_SHUTDOWN; gnome-session-quit --power-off) &
fi
