# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/98da40a4-d12f-4f88-aa8b-a0d2f48a368b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-464dc1b6-1d50-456f-ad9b-b90612a0f10a".device = "/dev/disk/by-uuid/464dc1b6-1d50-456f-ad9b-b90612a0f10a";
  boot.initrd.luks.devices."luks-ea48c8e6-b816-4f5f-ab03-45ad58d4a1f5".device = "/dev/disk/by-uuid/ea48c8e6-b816-4f5f-ab03-45ad58d4a1f5";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6ABB-5D59";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/71204be4-3c8d-490f-9ab1-ac70af6f1ccb"; }
    ];

  services.displayManager.autoLogin = {
    enable = true;
    user = "viv";
  };

  # power saving settings
  services.power-profiles-daemon.enable = false;
  powerManagement.enable = true;
  services.thermald.enable = true;
  services.auto-cpufreq.enable = true;
  services.auto-cpufreq.settings = {
    battery = {
       governor = "powersave";
       turbo = "never";
    };
    charger = {
       governor = "performance";
       turbo = "auto";
    };
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
