# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/df664ebc-dc58-431e-adad-65c811159440";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-b13e350b-d528-4a47-8aa9-e08794a9d90b".device = "/dev/disk/by-uuid/b13e350b-d528-4a47-8aa9-e08794a9d90b";
  boot.initrd.luks.devices."luks-3d6a2802-dac3-4e31-bf1b-6e9770ffcffd".device = "/dev/disk/by-uuid/3d6a2802-dac3-4e31-bf1b-6e9770ffcffd";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4CDD-BA64";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2816b194-3914-4a85-a0e4-4cde63219192"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
