[general]
autostart = ["noctalia"]

[input.keybinds]
Mod = "overview-toggle"
"Mod+Q" = "window-close"
"Mod+Return" = "spawn:ghostty"
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+W" = "spawn:librewolf"
"Mod+XF86AudioMute" = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
XF86AudioLowerVolume = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
XF86AudioRaiseVolume = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
XF86MonBrightnessDown = "spawn:noctalia msg brightness-down 10"
XF86MonBrightnessUP = "spawn:noctalia msg brightness-up 10"

[input.keyboard]
layout = "gb"

[input.touchpad]
disable_while_typing = true
natural_scroll = true

[keybinds]
Mod = "overview-toggle"
"Mod+M" = "window-toggle-maximize-to-edges"
"Mod+Q" = "window-close"
"Mod+Return" = "spawn:ghostty"
"Mod+Space" = "spawn:noctalia msg panel-toggle launcher"
"Mod+W" = "spawn:librewolf"
"Mod+XF86AudioMute" = "spawn:wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
XF86AudioLowerVolume = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
XF86AudioRaiseVolume = "spawn:wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
XF86MonBrightnessDown = { action = "spawn:noctalia msg brightness-down 10", allow_when_locked = true }
XF86MonBrightnessUp = { action = "spawn:noctalia msg brightness-up 10", allow_when_locked = true }

[layout]
gap = 4
mode = "scrolling"
