{self, inputs, ...}:
{
  flake.nixosModules.smolBoogalooHardware = { config, lib, pkgs, modulesPath, ... }:
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "smolBoogaloo";
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-94c1c9a9-e3e4-4f19-b01c-cb259722ca06";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-94c1c9a9-e3e4-4f19-b01c-cb259722ca06".device = "/dev/disk/by-uuid/94c1c9a9-e3e4-4f19-b01c-cb259722ca06";
  boot.initrd.luks.devices."luks-8d8defd0-b71b-4332-b554-fe874ba0bfdc".device = "/dev/disk/by-uuid/8d8defd0-b71b-4332-b554-fe874ba0bfdc";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DD2C-FBE4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-8d8defd0-b71b-4332-b554-fe874ba0bfdc"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}
