{self, inputs, ...}:
{
  flake.nixosModules.smolBoogalooHardware = { config, lib, pkgs, modulesPath, ... }:
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "smolBoogaloo";
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-90d8b754-28a6-473a-a06e-933dafa7ea57";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-90d8b754-28a6-473a-a06e-933dafa7ea57".device = "/dev/disk/by-uuid/90d8b754-28a6-473a-a06e-933dafa7ea57";
  boot.initrd.luks.devices."luks-72fe1ff7-8cfb-4cf2-a42e-498f825cbf2e".device = "/dev/disk/by-uuid/72fe1ff7-8cfb-4cf2-a42e-498f825cbf2e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A5F6-D32F";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-72fe1ff7-8cfb-4cf2-a42e-498f825cbf2e"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
};
}
