[mgr]
prepend_keymap = [
  { on = "<S-t>", run = 'shell --orphan --confirm ghostty', desc = "Just for test!" },
  { on = "<Right>", run = 'noop', desc = "Just for test!" },
  { on = "<Left>", run = 'noop', desc = "Just for test!" },
  { on = "<Up>", run = 'noop', desc = "Just for test!" },
  { on = "<down>", run = 'noop', desc = "Just for test!" },
]
